on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing how it works
    steps:
      - name: Hello world action step
        uses: DarkHole1/phpunit-junit-action@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
