on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing how it works
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
